#ifndef READERVIEW0_VERSION_H
#define READERVIEW0_VERSION_H

#define READERVIEW0_VERSION_MAJOR 0
#define READERVIEW0_VERSION_MINOR 2
#define READERVIEW0_VERSION_PATCH 0
#define READERVIEW0_VERSION_STRING "0.2.0-dev"

#define READERVIEW0_API_VERSION 2
#define READERVIEW0_UI0_REQUIRED_API_VERSION 90

#endif /* READERVIEW0_VERSION_H */
